const areas=[
{id:'historic',name:'Historic Centre',status:'good',statusLabel:'Recommended',lat:36.7211,lng:-4.4216,tagline:'The heart of Málaga',summary:'Best if you want to walk out of your accommodation and immediately find restaurants, wine bars, cafés and beautiful streets.',best:'Couples, groups of friends and guests who want to be in the middle of everything.',tip:'For a wedding weekend, the Cathedral and southern part of the centre are especially convenient. Light sleepers should favour a quieter side street rather than directly above a bar or restaurant.',streets:['Calle Larios','Plaza de la Constitución','Cathedral','Plaza del Siglo','Plaza de Uncibay','Calle Carretería'],card:'Walkable, lively and ideal if you want Málaga on your doorstep.'},
{id:'soho',name:'Soho',status:'good',statusLabel:'Recommended',lat:36.7159,lng:-4.4238,tagline:'Central, creative & slightly more relaxed',summary:'A strong choice if you want to stay central without being right in the busiest part of the Historic Centre.',best:'Couples and friends looking for a central location with a more modern atmosphere.',tip:'The southern part of Soho, towards the port, works especially well for combining the centre with evening walks around Muelle Uno.',streets:['Alameda Principal','Calle Casas de Campos','Calle Tomás Heredia','Towards the port'],card:'Central and stylish, with a calmer feel than the old town.'},
{id:'malagueta',name:'La Malagueta & Muelle Uno',status:'good',statusLabel:'Recommended',lat:36.7180,lng:-4.4080,tagline:'The best option for city + sea',summary:'A great choice if you want to wake up near the Mediterranean while still being able to walk into the centre.',best:'Guests who want the sea, especially if they are staying a few extra days around the wedding.',tip:'Look around La Malagueta / Paseo de Reding / Muelle Uno rather than going too far east.',streets:['Paseo de la Farola','Paseo de Reding','Calle San Nicolás','Calle Maestranza','Paseo Marítimo Ciudad de Melilla','Calle Vélez-Málaga'],card:'Beach, port and Historic Centre all within easy reach.'},
{id:'limonar',name:'El Limonar & La Caleta',status:'good',statusLabel:'Recommended',lat:36.7226,lng:-4.3952,tagline:'Quiet, elegant & residential',summary:'One of Málaga’s most refined residential areas, with tree-lined streets, elegant homes and a calmer atmosphere than the centre.',best:'Couples, families and guests looking for a peaceful, elegant stay with a more local feel.',tip:'Stay lower down near the seafront if you want to walk to the beach. Go uphill for larger villas, accepting greater reliance on taxis or buses.',streets:['Paseo de Reding','Paseo de Sancha','La Caleta','Lower El Limonar','Upper El Limonar for villas'],card:'A polished, peaceful option for guests who value space and calm.'},
{id:'pedregalejo',name:'Pedregalejo',status:'good',statusLabel:'Recommended',lat:36.7201,lng:-4.3688,tagline:'Málaga’s seaside village feel',summary:'A local Mediterranean option with small beaches, fishermen’s houses, restaurants, chiringuitos and cafés along the promenade.',best:'Guests staying several nights who want a more local seaside experience, or families and groups looking for a larger property.',tip:'Stay near the seafront for the classic Pedregalejo experience. Look uphill for villas, more privacy and sea views.',streets:['Pedregalejo seafront','Promenade','Hillside villas'],card:'Local, relaxed and seaside-focused, with good options for larger groups.'},
{id:'perchel',name:'Perchel & Huelin',status:'good',statusLabel:'Recommended',lat:36.7088,lng:-4.4387,tagline:'Good value, transport & beach access',summary:'A practical alternative if you want more affordable accommodation while staying relatively close to the centre, station, port and beach.',best:'Guests looking for better value, guests arriving by train, or anyone planning day trips along the coast.',tip:'Look around Perchel / María Zambrano / Huelin, especially towards the beach rather than too far west.',streets:['Perchel','María Zambrano','Huelin','Towards Huelin Beach'],card:'The sensible value choice with excellent connections.'},
{id:'trinidad',name:'La Trinidad',status:'check',statusLabel:'Check exact street',lat:36.7256,lng:-4.4303,tagline:'Very close — but street-by-street',summary:'Geographically close to the Historic Centre, but the atmosphere can change considerably from one street to another.',best:'Only consider it after checking the exact accommodation pin and surroundings.',tip:'If a property looks significantly cheaper because it is advertised as close to the centre, inspect the exact street carefully before booking.',streets:['Check exact street before booking'],card:'Close on the map, but not a blanket yes.'},
{id:'victoria',name:'Cruz Verde / Upper Victoria',status:'check',statusLabel:'Check exact street',lat:36.7264,lng:-4.4165,tagline:'Calle Victoria can work; west/uphill needs checking',summary:'Calle Victoria itself can be a good choice, especially closer to the centre. The fit changes as you move further west or uphill.',best:'Guests who find a strong property on Calle Victoria or very close to the centre.',tip:'For accommodation further west of Calle Victoria or uphill, check the exact location and surroundings before booking.',streets:['Calle Victoria near centre','West of Calle Victoria: check','Further uphill: check'],card:'Conditional: Calle Victoria can be fine, but west/uphill deserves a location check.'},
{id:'ollerias',name:'Ollerías / Behind Carretería',status:'avoid',statusLabel:'Not recommended',lat:36.7250,lng:-4.4229,tagline:'Use Calle Carretería as your northern limit',summary:'For this wedding weekend, accommodation north of Calle Carretería around Ollerías is not an area the guide would choose for guests.',best:'Choose a property south of Calle Carretería instead.',tip:'If the accommodation is behind Calle Carretería, check the location before booking or choose another base.',streets:['Calle Ollerías','North / behind Calle Carretería'],card:'Too easy to mistake for Centro; stay south of Carretería instead.'},
{id:'ciudadjardin',name:'Ciudad Jardín',status:'avoid',statusLabel:'Poor fit for this trip',lat:36.7468,lng:-4.4215,tagline:'Not a problem area — simply inconvenient',summary:'Primarily residential and further from the centre, so guests are less able to walk everywhere and more dependent on taxis or buses.',best:'Only choose it if you have a specific reason to stay there.',tip:'For a short wedding weekend, use the same budget for somewhere closer to the centre.',streets:['North-east of the centre'],card:'Not a safety warning; simply a weak choice for a short wedding weekend.'},
{id:'palmilla',name:'La Palma / Palma-Palmilla',status:'avoid',statusLabel:'Strongly avoid for guests',lat:36.7420,lng:-4.4355,tagline:'Choose another area for wedding guests',summary:'Although it can look relatively close to the centre and La Rosaleda on a map, the guide strongly recommends choosing another area for tourists and wedding guests.',best:'Wedding guests should base themselves in one of the recommended areas instead.',tip:'If you find accommodation near La Rosaleda or north of the Historic Centre, check the precise location carefully before confirming.',streets:['Near La Rosaleda: check exact location','North of Historic Centre: verify carefully'],card:'The clearest choose-somewhere-else recommendation in the guide.'}
];
const map=L.map('map',{zoomControl:true,scrollWheelZoom:false}).setView([36.722,-4.416],13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const markers=new Map();
function markerIcon(a){return L.divIcon({className:'',html:`<div class="custom-pin ${a.status}"><span>${a.status==='good'?'✓':a.status==='check'?'?':'!'}</span></div>`,iconSize:[34,34],iconAnchor:[17,32],popupAnchor:[0,-30]})}
areas.forEach(a=>{const m=L.marker([a.lat,a.lng],{icon:markerIcon(a)}).addTo(map);m.bindPopup(`<strong>${a.name}</strong><br>${a.card}`);m.on('click',()=>selectArea(a.id,true));markers.set(a.id,m)});
const detailCard=document.getElementById('detailCard'),areaGrid=document.getElementById('areaGrid'),areaSelect=document.getElementById('areaSelect'),statusFilter=document.getElementById('statusFilter');
function detailHTML(a){return `<span class="status ${a.status}">${a.statusLabel}</span><h2>${a.name}</h2><p class="tagline">${a.tagline}</p><div class="detail-grid"><div class="detail-block"><h3>Why choose it</h3><p>${a.summary}</p></div><div class="detail-block"><h3>Best for</h3><p>${a.best}</p></div><div class="detail-block"><h3>Local tip</h3><p>${a.tip}</p></div><div class="detail-block"><h3>Useful reference points</h3><div class="street-list">${a.streets.map(s=>`<span class="street">${s}</span>`).join('')}</div></div></div>`}
function renderCards(){areaGrid.innerHTML=areas.map(a=>`<article class="area-card" data-id="${a.id}" data-status="${a.status}"><div class="mini-status">${a.statusLabel}</div><h3>${a.name}</h3><p>${a.card}</p><div class="fit">${a.tagline}</div></article>`).join('');areaGrid.querySelectorAll('.area-card').forEach(c=>c.addEventListener('click',()=>selectArea(c.dataset.id,true)))}
function selectArea(id,move=false){const a=areas.find(x=>x.id===id);if(!a)return;detailCard.innerHTML=detailHTML(a);document.querySelectorAll('.area-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===id));if(move){map.flyTo([a.lat,a.lng],['pedregalejo','ciudadjardin','palmilla'].includes(a.id)?14:15,{duration:.6});markers.get(id).openPopup()}}
function applyFilters(){const s=statusFilter.value;document.querySelectorAll('.area-card').forEach(c=>{const show=s==='all'||c.dataset.status===s;c.classList.toggle('hidden',!show);const m=markers.get(c.dataset.id);if(show&&!map.hasLayer(m))m.addTo(map);if(!show&&map.hasLayer(m))map.removeLayer(m)})}
areaSelect.addEventListener('change',()=>{const id=areaSelect.value;if(id==='all'){map.flyTo([36.722,-4.416],13,{duration:.6});return}const a=areas.find(x=>x.id===id);if(!a)return;if(statusFilter.value!=='all'&&statusFilter.value!==a.status){statusFilter.value='all';applyFilters()}selectArea(id,true);detailCard.scrollIntoView({behavior:'smooth',block:'nearest'})});
statusFilter.addEventListener('change',()=>{areaSelect.value='all';applyFilters()});
document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(b=>b.classList.toggle('active',b===btn));const a=areas.find(x=>x.id===btn.dataset.match);const r=document.getElementById('matchResult');r.innerHTML=`<strong>${a.name}</strong> — ${a.card}`;r.classList.add('show');selectArea(a.id,true);detailCard.scrollIntoView({behavior:'smooth',block:'nearest'})}));
renderCards();selectArea('malagueta');setTimeout(()=>map.invalidateSize(),100);